name: "Initiate workflow"

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  yarn-install:
    name: "Install dependencies"
    uses: ./.github/workflows/dev_on_workflow_install.yml
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
  yarn-tester:
    name: "Run unit tests"
    needs: yarn-install
    uses: ./.github/workflows/dev_on_workflow_tester.yml
    secrets:
      GCP_EHP_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      GCP_EHP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
